### ISSUE TITLE
Recursive modules with inferred implementation do not have links to source

### ISSUE THREAD

**Issue by panglesd** [panglesd/odoc#10]
In `Odoc_model.Lang.ModuleType`, there is currently no link to source, which is strange.

See https://choum.net/panglesd/source_demo/odoc/odoc_model/Odoc_model/Lang/ModuleType/index.html if it is still there.

**Comment by Julow** [comment]
Note: These modules are all mutually recursive. Working fine for `Lang.Locations` which is not recursive.

**Comment by panglesd** [comment]
We might solve this after the first integration, but we should at least add a test.

**Comment by panglesd** [comment]
Actually, recursive modules do have links to source.

However, they do not when there is no implementation, that is, when the implementation is inferred from the signature, when there is only types defined and the syntax is:

```
module rec A : sig type t =... type u = ... module type S = ... end = A
and B : sig ... end = B
```

In this case, it makes sense not to have jump to implementation as there is no implementation. What we could have is jump to declaration, but that's another story (and it's not useful here: there is no additional information in the signature of a module than in the odoc page for the module).
