### ISSUE TITLE
Lexing of doc comments

### ISSUE THREAD

**Issue by Julow** [panglesd/odoc#11]
A line of source code picked in Lang:
```html
<span id="L39" class="source_line"></span>(** {3 Modules} <span class="DOCSTRING">*)</span><span class="EOL">
</span>
```

The closing of the comment is lexed as a docstring but not the beginning and the body of the comment, which are raw text.

**Comment by panglesd** [comment]
fixed in e113bc73b96e1102cdc268220f2d2e753a219861
