### ISSUE TITLE
Working well with cppo and preprocessors

### ISSUE THREAD

**Issue by panglesd** [panglesd/odoc#12]
We need to think about it: which file should be visible (the (string) preprocessed or not preprocessed?)

The preprocessed seems more technically adequate (I guess all locations point to this one)

The non-preprocessed might be richer (for instance, with cppo `#if` it can contains code for more platforms/ocaml versions).

**Comment by Julow** [comment]
There's only one adequate source: the one where all locations make sense. This is critical to have correct links. No other source can be considered.

In the case of cppo, it perhaps put line directives ? In this case, the original source is the right one.
In case of a string preprocessor, it's unclear. There might not be any source code that make sense to us.

**Comment by panglesd** [comment]
Superseded by #15
