### ISSUE TITLE
Source is not collected deep enough

### ISSUE THREAD

**Issue by panglesd** [panglesd/odoc#18]
The `in_sig` function collecting all sources is not going deeper than the module.

I think that it would be better to add sources to `named_expansion` rather than traversing the Lang, collecting all sources.

**Comment by Julow** [comment]
If we add sources to `named_expansion`, we should move the collection into document, at the time of looking up subpages.

**Comment by panglesd** [comment]
Fixed in fba0b043e3366e7cb9f20c87c32eb92d3a62028a
