### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by panglesd** [panglesd/odoc#19]
We should test at least:

- [x] Include sources in existing generator tests
- [x] Class
- [x] Class types
- [x] Collecting sources deep (expansion in expansion)
- [x] Functor result
- [x] Functor parameter
- [x] All loading mechanism such as `cmt`, `cmi` and `cmti`.

**Comment by panglesd** [comment]
I added a simple test for functor results, expansion, and parameter in e18b1079a05204d0c7c82dafcc1901d6c846731a. Might not be sufficient since #20 is not caught (or, #20 has nothing to do with functor parameter).

**Comment by Julow** [comment]
This is done :)
