### ISSUE TITLE
add source anchors to Nested

### ISSUE THREAD

**Issue by panglesd** [panglesd/odoc#25]
Constructors have locations and should have a source anchor (extension does not have a loc)

**Comment by Julow** [comment]
Fixed in 4a248be13. A source anchor on Nested is not needed and would create a lot of links. Instead, we generate one link for the whole item, pointing to the first constructor.

**Comment by panglesd** [comment]
We decided to use the location of the first extension constructor to the whole declaration instead of adding source locations to Nested.
